-- migrate:up
ALTER TABLE users ADD COLUMN college VARCHAR(255);

ALTER TABLE users ADD CONSTRAINT check_college_validity CHECK (college IN (
    '6th of October University',
    'Ain Shams University - Faculty of Agriculture',
    'Ain Shams University - Faculty of Al-Alsun (Languages)',
    'Ain Shams University - Faculty of Archaeology',
    'Ain Shams University - Faculty of Arts',
    'Ain Shams University - Faculty of Business',
    'Ain Shams University - Faculty of Computer and Information Sciences',
    'Ain Shams University - Faculty of Dentistry',
    'Ain Shams University - Faculty of Education',
    'Ain Shams University - Faculty of Engineering',
    'Ain Shams University - Faculty of Law',
    'Ain Shams University - Faculty of Media and Mass Communication',
    'Ain Shams University - Faculty of Medicine',
    'Ain Shams University - Faculty of Nursing',
    'Ain Shams University - Faculty of Pharmacy',
    'Ain Shams University - Faculty of Science',
    'Ain Shams University - Faculty of Specific Education',
    'Ain Shams University - Faculty of Veterinary Medicine',
    'Ain Shams University - Faculty of Women',
    'Al-Azhar University',
    'Alexandria University - Faculty of Agriculture',
    'Alexandria University - Faculty of Arts',
    'Alexandria University - Faculty of Business',
    'Alexandria University - Faculty of Computing and Data Science',
    'Alexandria University - Faculty of Dentistry',
    'Alexandria University - Faculty of Education',
    'Alexandria University - Faculty of Engineering',
    'Alexandria University - Faculty of Fine Arts',
    'Alexandria University - Faculty of Law',
    'Alexandria University - Faculty of Medicine',
    'Alexandria University - Faculty of Nursing',
    'Alexandria University - Faculty of Pharmacy',
    'Alexandria University - Faculty of Physical Education',
    'Alexandria University - Faculty of Science',
    'Alexandria University - Faculty of Tourism and Hotels',
    'Alexandria University - Faculty of Veterinary Medicine',
    'American University in Cairo (AUC)',
    'Assiut University',
    'Aswan University',
    'Banha University',
    'Beni-Suef University',
    'British University in Egypt (BUE)',
    'Cairo University - Faculty of Agriculture',
    'Cairo University - Faculty of Archaeology',
    'Cairo University - Faculty of Arts',
    'Cairo University - Faculty of Commerce',
    'Cairo University - Faculty of Computers and Artificial Intelligence',
    'Cairo University - Faculty of Dar El-Ulum',
    'Cairo University - Faculty of Early Childhood Education',
    'Cairo University - Faculty of Economics and Political Science',
    'Cairo University - Faculty of Engineering',
    'Cairo University - Faculty of Law',
    'Cairo University - Faculty of Mass Communication',
    'Cairo University - Faculty of Medicine',
    'Cairo University - Faculty of Nursing',
    'Cairo University - Faculty of Oral and Dental Medicine',
    'Cairo University - Faculty of Pharmacy',
    'Cairo University - Faculty of Physical Therapy',
    'Cairo University - Faculty of Science',
    'Cairo University - Faculty of Specific Education',
    'Cairo University - Faculty of Veterinary Medicine',
    'Damanhour University',
    'Damietta University',
    'Egypt-Japan University of Science & Technology',
    'Fayoum University',
    'French University in Egypt',
    'Future University in Egypt',
    'German University in Cairo (GUC)',
    'Helwan University',
    'Kafrelsheikh University',
    'Luxor University',
    'Mansoura University',
    'Menoufia University',
    'Military Technical College',
    'Minia University',
    'Misr International University (MIU)',
    'Misr University for Science and Technology (MUST)',
    'Modern Sciences and Arts University (MSA)',
    'New Valley University',
    'Nile University',
    'Port Said University',
    'Sadat Academy for Management Sciences',
    'Sohag University',
    'South Valley University',
    'Suez Canal University',
    'Suez University',
    'Tanta University',
    'Zagazig University',
    'Zewail City of Science & Technology'
));

-- migrate:down
ALTER TABLE users DROP CONSTRAINT check_college_validity;
ALTER TABLE users DROP COLUMN college;

